TOP_MODULE = dvi_decoder
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../provided_modules/dff.sv
SYNTH_SOURCES += ../provided_modules/inv.sv
SYNTH_SOURCES += ../provided_modules/jstk/PmodJSTK.sv
SYNTH_SOURCES += ../provided_modules/jstk/spiCtrl.v
SYNTH_SOURCES += ../provided_modules/jstk/ClkDiv_20Hz.sv
SYNTH_SOURCES += ../provided_modules/jstk/ClkDiv_66_67kHz.sv
SYNTH_SOURCES += ../provided_modules/jstk/spiMode0.v
SYNTH_SOURCES += display_clock.sv
SYNTH_SOURCES += input_de_sync.sv
SYNTH_SOURCES += screens_state_machine.sv
SYNTH_SOURCES += display_480p.sv
SYNTH_SOURCES += simple_480p.sv
SYNTH_SOURCES += rom_async.sv
SYNTH_SOURCES += counter.sv
SYNTH_SOURCES += sprite_inline.sv
SYNTH_SOURCES += pacman_orientation.sv
SYNTH_SOURCES += score.sv
SYNTH_SOURCES += score2.sv
SYNTH_SOURCES += timer.sv
SYNTH_SOURCES += edge_detector.sv
SYNTH_SOURCES += shift.sv
SYNTH_SOURCES += lsfr.sv
NONSYNTH_SOURCES += ../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../provided_modules/nonsynth_reset_gen.sv
-include ../simulation.mk
-include ../fpga.mk

